export const ARTIFACT_REGEX =
  /<artifact\s+identifier="([^"]+)"[,\s]+title="([^"]+)"[,\s]+type="([^"]+)">\s*([\s\S]*?)\s*<\/artifact>/g;

export const MIME_TYPES: Record<string, string> = {
  // Documents
  pdf: "application/pdf",
  doc: "application/msword",
  docx: "application/msword",
  rtf: "application/rtf",
  // Data formats
  json: "application/json",
  csv: "text/csv",
  tsv: "text/tab-separated-values",
  xml: "application/xml",
  yaml: "text/yaml",
  yml: "text/yaml",
  toml: "text/plain",
  // Web
  html: "text/html",
  css: "text/css",
  js: "text/javascript",
  jsx: "text/javascript",
  ts: "text/typescript",
  tsx: "text/typescript",
  // Markup / text
  md: "text/markdown",
  txt: "text/plain",
  log: "text/plain",
  ini: "text/plain",
  cfg: "text/plain",
  env: "text/plain",
  // Images
  svg: "image/svg+xml",
  // Programming languages
  py: "text/x-python",
  java: "text/x-java",
  c: "text/x-c",
  h: "text/x-c",
  cpp: "text/x-c++",
  hpp: "text/x-c++",
  cs: "text/x-csharp",
  go: "text/x-go",
  rs: "text/x-rust",
  rb: "text/x-ruby",
  php: "text/x-php",
  swift: "text/x-swift",
  kt: "text/x-kotlin",
  scala: "text/x-scala",
  lua: "text/x-lua",
  r: "text/x-r",
  m: "text/x-matlab",
  // Shell / config
  sh: "text/x-shellscript",
  bash: "text/x-shellscript",
  zsh: "text/x-shellscript",
  ps1: "text/plain",
  bat: "text/plain",
  // Database / query
  sql: "text/x-sql",
  graphql: "text/plain",
  gql: "text/plain",
  // Other
  dockerfile: "text/plain",
  makefile: "text/plain",
  gitignore: "text/plain",
  tex: "text/x-latex",
  bib: "text/x-bibtex",
};

/** Map from artifact `type` field to file extension (when title has no extension) */
export const TYPE_TO_EXTENSION: Record<string, string> = {
  pdf: "pdf",
  doc: "doc",
  docx: "doc",
  json: "json",
  csv: "csv",
  tsv: "tsv",
  xml: "xml",
  svg: "svg",
  html: "html",
  css: "css",
  markdown: "md",
  md: "md",
  text: "txt",
  txt: "txt",
  yaml: "yaml",
  yml: "yaml",
  toml: "toml",
  sql: "sql",
  graphql: "graphql",
  // Programming languages
  typescript: "ts",
  javascript: "js",
  python: "py",
  java: "java",
  go: "go",
  rust: "rs",
  c: "c",
  cpp: "cpp",
  csharp: "cs",
  php: "php",
  ruby: "rb",
  swift: "swift",
  kotlin: "kt",
  scala: "scala",
  lua: "lua",
  r: "r",
  matlab: "m",
  bash: "sh",
  shell: "sh",
  powershell: "ps1",
  batch: "bat",
  dockerfile: "Dockerfile",
  makefile: "Makefile",
  latex: "tex",
  tex: "tex",
  rtf: "rtf",
};

export const CODE_TYPES = [
  "typescript",
  "javascript",
  "python",
  "java",
  "go",
  "rust",
  "html",
  "css",
  "sql",
  "bash",
  "yaml",
  "xml",
  "c",
  "cpp",
  "csharp",
  "php",
  "ruby",
  "swift",
  "kotlin",
  "scala",
  "lua",
  "r",
  "matlab",
  "shell",
  "powershell",
  "graphql",
  "dockerfile",
  "makefile",
  "latex",
  "toml",
] as const;
