import type { DocStructure } from "../types";

/**
 * Generates a Word-compatible HTML document saved as .doc.
 * Word, LibreOffice, and Google Docs all open this format natively.
 * Uses styled headings with accent colors matching the PDF generator palette.
 */

const SECTION_COLORS = [
  { accent: "#2980b9", bg: "#edf4fb" }, // blue
  { accent: "#219775", bg: "#edfaf5" }, // teal
  { accent: "#9c59b6", bg: "#f5effc" }, // purple
  { accent: "#d97826", bg: "#fcf4ed" }, // orange
  { accent: "#c23d59", bg: "#fceff1" }, // rose
  { accent: "#339944", bg: "#f0faf0" }, // green
];

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/\n/g, "<br/>");
}

export function generateDocx(content: string): Blob {
  let docData: DocStructure;
  try {
    docData = JSON.parse(content) as DocStructure;
  } catch {
    docData = { title: "Document", sections: [{ body: content }] };
  }

  const sections = docData.sections ?? [];

  const bodyHtml = sections
    .map((section, idx) => {
      const color = SECTION_COLORS[idx % SECTION_COLORS.length];
      let html = "";
      if (section.heading) {
        html += `<div style="background:${color.bg};border-left:4px solid ${color.accent};padding:8pt 12pt;margin-top:18pt;margin-bottom:8pt;border-radius:0 4px 4px 0;">
  <h2 style="font-size:14pt;color:${color.accent};margin:0;font-family:Calibri,Arial,sans-serif;font-weight:bold;">${escapeHtml(section.heading)}</h2>
</div>`;
      }
      if (section.body) {
        html += `<p style="font-size:11pt;line-height:1.7;color:#333;margin-bottom:10pt;margin-top:4pt;padding-left:4pt;font-family:Calibri,Arial,sans-serif;">${escapeHtml(section.body)}</p>`;
      }
      return html;
    })
    .join("\n");

  const metaLine =
    docData.author || docData.createdAt
      ? `<p style="font-size:9pt;color:#888;margin-bottom:4pt;font-family:Calibri,Arial,sans-serif;">${escapeHtml([docData.author, docData.createdAt].filter(Boolean).join(" — "))}</p>`
      : "";

  const titleBlock = docData.title
    ? `<div style="background:#1a365d;padding:16pt 20pt;margin:-1in -1in 0 -1in;margin-bottom:14pt;">
  <h1 style="font-size:22pt;color:#ffffff;margin:0;font-family:Calibri,Arial,sans-serif;font-weight:bold;">${escapeHtml(docData.title)}</h1>
  ${metaLine ? `<p style="font-size:9pt;color:#b0c4de;margin:4pt 0 0 0;font-family:Calibri,Arial,sans-serif;">${escapeHtml([docData.author, docData.createdAt].filter(Boolean).join(" — "))}</p>` : ""}
</div>`
    : "";

  const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="utf-8">
<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Gemma Chat">
<!--[if gte mso 9]>
<xml>
<o:DocumentProperties>
${docData.title ? `<o:Title>${escapeHtml(docData.title)}</o:Title>` : ""}
${docData.author ? `<o:Author>${escapeHtml(docData.author)}</o:Author>` : ""}
</o:DocumentProperties>
</xml>
<![endif]-->
<style>
  @page { size: A4; margin: 1in; }
  body { font-family: Calibri, Arial, sans-serif; color: #222; }
  table { border-collapse: collapse; }
</style>
</head>
<body>
${titleBlock}
${!docData.title && metaLine ? metaLine + '<hr style="border:none;border-top:1px solid #ddd;margin-bottom:14pt;"/>' : ""}
${bodyHtml}
<div style="margin-top:24pt;border-top:1px solid #ccc;padding-top:8pt;">
  <p style="font-size:8pt;color:#999;text-align:center;font-family:Calibri,Arial,sans-serif;">Generated by Gemma Chat</p>
</div>
</body>
</html>`;

  return new Blob([html], { type: "application/msword" });
}
